version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - bash ./scripts/install_fonts.sh

python:
  install:
    - method: pip
      path: .[doc]
      
sphinx:
  configuration: doc/conf.py
