version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - |
        if ! command -v sudo &>/dev/null; then
          echo "sudo is not installed. Installing sudo..."
          apt-get update
          apt-get install -y sudo
        else
          echo "sudo is already installed."
        fi
      - bash ./scripts/install_fonts.sh

python:
  install:
    - method: pip
      path: .[doc]

sphinx:
  configuration: doc/conf.py
