version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - bash ./scripts/install_fonts.sh
    post_install:
      - plotly_get_chrome -y
      - echo "export KAL_CHROME_PATH=$HOME/.plotly/kaleido/chrome/chrome" >> $HOME/.bashrc
      - export KAL_CHROME_PATH=$HOME/.plotly/kaleido/chrome/chrome

python:
  install:
    - method: pip
      path: .[doc]
      
sphinx:
  configuration: doc/conf.py
