version: 2

build:
  image: latest  # Use the latest RTD build image
  apt_packages:
    - libnss3
    - libatk-bridge2.0-0
    - libcups2
    - libxcomposite1
    - libxdamage1
    - libxfixes3
    - libxrandr2
    - libgbm1
    - libxkbcommon0
    - libpango-1.0-0
    - libcairo2
    - libasound2

python:
  install:
    - method: pip
      path: .[doc]

sphinx:
  configuration: doc/conf.py
