version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  jobs:
    pre_install:
      # Install fonts
      - bash ./scripts/install_fonts.sh

      # Install OS dependencies needed for Chromium/Kaleido
      - sudo apt-get update -y
      - sudo apt-get install -y \
        libnss3 \
        libatk-bridge2.0-0 \
        libcups2 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        libgbm1 \
        libxkbcommon0 \
        libpango-1.0-0 \
        libcairo2 \
        libasound2

python:
  install:
    - method: pip
      path: .[doc]

sphinx:
  configuration: doc/conf.py
