name: Install and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matplotlib:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Repository and Dependencies
      run: |
        pip3 install .[test]

    - name: Install Font(s)
      run: |
        ./scripts/install_fonts.sh

    - name: Download Input Data
      run: |
        (cd input_data && ./get_data.sh)

    - name: Run Tests
      run: |
        (cd tests/matplotlib && testflo -v .)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: matplotlib-artifacts
        path: |
          # Specify paths to generated files or directories
          tests/matplotlib/*
          # Add other paths as necessary

  plotly:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Repository and Dependencies
      run: |
        pip3 install .[test]

    - name: Install Font(s)
      run: |
        ./scripts/install_fonts.sh

    - name: Download Input Data
      run: |
        (cd input_data && ./get_data.sh)

    - name: Run Tests
      run: |
        (cd tests/plotly && testflo -v .)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plotly-artifacts
        path: |
          tests/plotly/*
          # Add other paths as necessary

  download-artifacts:
    runs-on: ubuntu-22.04
    needs: [matplotlib, plotly]  # Ensures this job runs after the previous jobs

    steps:
    - name: Download matplotlib artifacts
      uses: actions/download-artifact@v3
      with:
        name: matplotlib-artifacts
        path: ./artifacts/matplotlib

    - name: Download plotly artifacts
      uses: actions/download-artifact@v3
      with:
        name: plotly-artifacts
        path: ./artifacts/plotly
