name: Install and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matplotlib:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Repository and Dependencies
      run: |
        pip3 install .[test]

    - name: Download Input Data
      run: |
        (cd input_data && ./get_data.sh)

    - name: Run Tests
      run: |
        (cd tests/matplotlib && testflo -v .)
